const fs = require("node:fs");
const path = require("node:path");
const test = require("node:test");
const assert = require("node:assert/strict");

const root = path.join(__dirname, "..", "src", "web");

test("home dashboard maps overview data onto the stable memory lobby", () => {
  const html = fs.readFileSync(path.join(root, "public", "index.html"), "utf8");
  const app = fs.readFileSync(path.join(root, "public", "app.js"), "utf8");
  const adapter = fs.readFileSync(path.join(root, "public", "developer-kit", "home-dashboard.js"), "utf8");
  const styles = fs.readFileSync(path.join(root, "public", "developer-kit", "home-dashboard.css"), "utf8");
  const transition = fs.readFileSync(path.join(root, "public", "developer-kit", "page-transition.js"), "utf8");
  const transitionStyles = fs.readFileSync(path.join(root, "public", "developer-kit", "page-transition.css"), "utf8");
  const developerStyles = fs.readFileSync(path.join(root, "public", "theme-studio", "developer-common.css"), "utf8");

  assert.ok(html.indexOf("/app.js?v=") < html.indexOf("/developer-kit/home-dashboard.js?v=8"));
  assert.ok(html.indexOf("/developer-kit/page-transition.js?v=1") < html.indexOf("/app.js?v="));
  assert.match(adapter, /fetch\("\/api\/home"/);
  assert.match(adapter, /lastSync\(memory\.lastArchivedAt\)/);
  assert.doesNotMatch(adapter, /最近对话同步[^\n]*lastMinedAt/);
  assert.match(adapter, /今日纹路 · TODAY'S GRAIN/);
  assert.match(adapter, /const maintenanceOverdue = pendingMiningDays > 1/);
  assert.match(adapter, /library-card--mapped/);
  assert.match(adapter, /const dashboards = new WeakMap\(\)/);
  assert.doesNotMatch(adapter, /new WeakSet\(\)/);
  assert.match(adapter, /function renderDashboard\(lobby, data\)/);
  assert.match(adapter, /if \(existing\?\.data\) \{[\s\S]*?renderDashboard\(lobby, existing\.data\)/);
  assert.ok(adapter.indexOf("card.append(content)") < adapter.indexOf('card.classList.add("library-card--mapped")', adapter.indexOf("card.append(content)")));
  assert.match(adapter, /stone-mark--avatar/);
  assert.doesNotMatch(adapter, /stone-mark--hero/);
  const lobbyTemplate = app.match(/function lobby\(\)[\s\S]*?async function openLibrary/)?.[0] || "";
  assert.match(lobbyTemplate, /—— 蒲苇韧如丝，磐石无转移 ——/);
  assert.match(lobbyTemplate, /lobby stone-page-transition-pending/);
  assert.match(lobbyTemplate, /data-transition-message="正在整理今日纹路…" aria-busy="true"/);
  assert.doesNotMatch(lobbyTemplate, /topbar\(\)|<h1>你的记忆体<\/h1>/);
  assert.match(adapter, /M15 94C9 73 20 48 39 44/);
  assert.match(adapter, /M15 94C9 73 20 48 39 44[\s\S]*?fill="none"/);
  assert.doesNotMatch(adapter, /libraryName \|\| "记"\)\.slice/);
  assert.match(adapter, /if \(!memory\) return/);
  assert.doesNotMatch(adapter, /method:\s*["'](?:POST|PUT|PATCH|DELETE)/i);
  assert.match(styles, /\.today-grain-card/);
  assert.match(styles, /@media \(max-width: 680px\)/);
  assert.doesNotMatch(styles, /var\(--stone-(?!theme-)/);
  assert.match(styles, /\.lobby > \.shell\s*\{[\s\S]*?padding-top:\s*32px/);
  assert.match(styles, /\.today-grain-card\s*\{[\s\S]*?margin:\s*0 0 22px/);
  for (const method of ["begin", "complete", "fallback"]) assert.match(transition, new RegExp(`function ${method}\\(`));
  assert.match(transition, /window\.StonePageTransition/);
  assert.match(transitionStyles, /\.stone-page-transition-pending::before[\s\S]*?attr\(data-transition-message\)/);
  assert.match(adapter, /StonePageTransition\?\.begin/);
  assert.match(adapter, /StonePageTransition\?\.complete/);
  assert.match(adapter, /StonePageTransition\?\.fallback/);
  assert.match(styles, /\.lobby \.lobby-head p[\s\S]*?font:\s*600 16px/);
  assert.doesNotMatch(developerStyles, /today-grain-card/);
  assert.match(styles, /\.today-grain-card\s*\{[\s\S]*?linear-gradient/);
  assert.match(styles, /background: linear-gradient\(145deg, var\(--stone-theme-surface\)/);
  assert.doesNotMatch(styles, /color-mix\(/);
  assert.match(developerStyles, /color-mix\(in srgb, var\(--stone-theme-surface\) 92%, var\(--stone-theme-accent-soft\)\)/);
  assert.match(developerStyles, /background-image: radial-gradient\(circle at 18% 16%, color-mix\(in srgb, var\(--stone-theme-accent\) 18%, transparent\)/);
  assert.doesNotMatch(styles, /\.today-grain-card::before/);
});

test("memory creation uses one lightweight dialog instead of entering the legacy wizard", () => {
  const app = fs.readFileSync(path.join(__dirname, "..", "src", "web", "public", "app.js"), "utf8");
  const start = app.indexOf("function createMemoryDraft");
  const end = app.indexOf("function topbar", start);
  const creation = app.slice(start, end);
  assert.match(creation, /记忆体名字/);
  assert.match(creation, /AI 名字/);
  assert.match(creation, /用户名字/);
  assert.match(creation, /决定今后生成摘要和特征时关注什么/);
  assert.ok(creation.indexOf("生活监督") < creation.indexOf("情感陪伴"));
  assert.ok(creation.indexOf("情感陪伴") < creation.indexOf("编程日志"));
  assert.doesNotMatch(creation, />学习<|>陪伴<|>编程</);
  assert.match(creation, /创建并进入/);
  assert.match(creation, /升级旧版记忆体/);
  assert.match(creation, /layout-upgrade/);
  assert.doesNotMatch(creation, /resetCreateForm|wizard\(\)/);
});

test("home overview is a read-only endpoint and skips unconfigured memory drafts", () => {
  const server = fs.readFileSync(path.join(root, "server.js"), "utf8");
  assert.match(server, /req\.method === "GET" && url\.pathname === "\/api\/home"/);
  assert.match(server, /if \(!library\.configured \|\| !library\.threadId\) continue/);
  assert.match(server, /studyCount:/);
  assert.match(server, /libraries,/);
  assert.match(server, /SELECT MAX\(timestamp\) timestamp FROM messages WHERE thread_id=\?/);
  assert.match(server, /lastArchivedAt: latestArchived\?\.timestamp \|\| null/);
  assert.match(server, /archiveFullBytes: directoryBytes/);
  assert.match(server, /retainAnchors: Object\.keys/);
  assert.match(server, /eventAnchors: Object\.keys/);
});
